# Generated by Django 2.1.15 on 2020-02-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Hire date')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(upload_to='img/')),
                ('doc', models.ManyToManyField(to='management.Doctor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('director_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.Director')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department'),
        ),
    ]
